language: python
python:
  - '3.6'
sudo: required
services:
  - docker
install:
  - pip install twine
script:
  - make
  - twine upload dist/*
branches:
  only:
  - master
deploy:
  provider: pages
  skip-cleanup: true
  local-dir: gen-docs/html
  github-token: $GITHUB_TOKEN
  keep-history: false
  on:
    branch: master
